---
- hosts: lampserver
  become: true

  vars_files:
  - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
  
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  
  tasks: 
    - name: Get software for apt repository
      apt: "name={{ item }} state=present"
      with_items:
        - python-apt
        - python-pycurl
    
    - name: Add ondrej repository for later version of PHP
      apt_repository: repo='ppa:ondrej/php' update_cache=yes
    
    - name: Install Apache, MySQL, PHP and other dependencies
      apt: "name={{ item }} update_cache=yes state=latest"
      with_items:
        - git
        - curl
        - unzip
        - sendmail
        - apache2
        - php
        - php-mysql
        - libpcre3-dev
        - libapache2-mod-php
        - python-mysqldb
        - mysql-server

    - name: Disable firewall (for local dev only)
      service: name=ufw state=stopped
    
    - name: Start Apache, MySQL and PHP
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql